ls:
  .dir: kebab-case
  .tsx: kebab-case
  .ts: kebab-case
  .d.ts: kebab-case
  .test.ts: kebab-case
  .html: kebab-case
  .json: kebab-case
  .cjs.json: kebab-case
  .esm.json: kebab-case
  .node.json: kebab-case
  .workspace.json: kebab-case
  .package.ts: kebab-case
  .package.test.ts: kebab-case
  .config.ts: kebab-case
  .controller.ts: kebab-case
  .repository.ts: kebab-case
  .repository.test.ts: kebab-case
  .service.ts: kebab-case
  .entity.ts: kebab-case
  .model.ts: kebab-case
  .build.json: kebab-case

ignore:
  - .git
  - node_modules
  - build
  - frontend/node_modules
  - backend/node_modules
  - frontend/build
  - backend/build
  - shared/build
  - coverage
  - backend/logs
