ls:
  .dir: kebab-case
  .tsx: kebab-case
  .ts: kebab-case
  .d.ts: kebab-case
  .test.ts: kebab-case
  .html: kebab-case
  .json: kebab-case
  .workspace.json: kebab-case
  .package.ts: kebab-case
  .config.ts: kebab-case
  .controller.ts: kebab-case

ignore:
  - .git
  - node_modules
  - frontend/node_modules
  - backend/node_modules
  - coverage
  - backend/logs
