const EXIT_CODES = {
  SUCCESS: 0,
  FATAL: 1,
} as const;

const HTTP_CODES = {
  OK: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  INTERNAL_SERVER_ERROR: 500,
} as const;

export { EXIT_CODES, HTTP_CODES };
